config/routes.rb
Rails.application.routes.draw do

  resources :posts, only: [:index, :new, :create, :destroy]
  resources :users, only: [:new, :create]
  
  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'
  
  get '/signup', to: 'users#new'
  
  post '/signup', to: 'users#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  validates :body, presence: true, length: { minimum: 15 }
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  validates :name, presence: true
  validates :email, presence: true
  has_secure_password
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :get_user, only: [:new, :create]
  
  def index
    @posts = Post.all.includes(:user)
  end

  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new
    @post.body = params[:post][:body] # Why don't I need strong params here?
    @post.user_id = current_user.id
    if @post.save
      flash[:success] = "Post created!"
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    if @post.user == current_user
      @post.destroy
      flash[:success] = "Your post has been deleted!"
      redirect_to(root_path)
    else
      flash[:danger] = "You may only delete your own posts!"
      redirect_to(root_path)
    end
    
  end
  
  private
  
    def get_user
      if logged_in?
        @user = current_user
      else
        flash[:danger] = "You must be logged in."
        redirect_to login_path
      end
    end
    
    # def post_params
    #   params.require(:post).permit(:body)
    # end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      log_in(@user)
      flash[:success] = "Welcome, #{@user.name}!"
      redirect_to root_url
    else
      flash.now[:danger] = "Invalid email and/or password."
      render 'new'
    end
  end

  def destroy
    log_out
    flash[:success] = "You've been logged out."
    redirect_to root_url
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = "Welcome to Message Board, #{@user.name}!"
      redirect_to root_url
    else
      render "new"
    end
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Secret Board</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'shared/header' %>
      
      <div class="container-fluid">
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
      </div>
      
      <%= yield %>
      
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Post Board</h1>
<div class="container">
  <%= link_to "New Post", new_post_path, class: "btn btn-primary btn-block" %>
</div>

<div class="container">
  <% @posts.each do |post| %>
  
    <ul class="post">
      <li id="post-<%= post.id %>">
        <span class="content"><h2><%= post.body %><h2></h2></span>
        <% if logged_in? %>
          <span class="user">Posted by <%= post.user.name %></span>
        <% else %>
          <span class="user">Posted by <%= "Anonymous" %></span>
        <% end %>
        <span class="timestamp"><%= time_ago_in_words(post.created_at) %> ago.</span>
        <% if logged_in? && post.user_id == current_user.id %>
          <span class="delete"><%= link_to "delete", post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></span>
        <% end %>
      </li>
    </ul>
    
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<div class="container">
  

  <%= form_for(@post) do |f| %>
    <%= render 'shared/error_messages' %>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, rows: 5, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit "Submit Post", class: "btn btn-primary btn-lg" %>
    </div>
  <% end %>
  
</div>

app/views/shared/_error_messages.html.erb
<% if @post.errors.any? %>
  <div id="error_explaination">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@post.errors.count, "error") %>
    </div>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <%= link_to "Secret Board", root_path, class: "navbar-brand" %>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>

      <% if logged_in? %>
        <li><%= link_to "Logout", logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign up", signup_path %></li>
        <li><%= link_to "Login", login_path %></li>
      <% end %>

    </ul>
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="container">
  <%= form_for(@user, url: signup_url) do |f| %>

    <% if @user.errors.any? %>
      <div id="error_explaination">
        <div class="alert alert-danger">
          The form contains <%= pluralize(@user.errors.count, "error") %>
        </div>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, class:"form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.label :email %><br>
      <%= f.email_field :email, class:"form-control" %>
    </div>
      
    <div class="form-group">
      <%= f.label :password %><br>
      <%= f.password_field :password, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation, class:"form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.submit "Sign up", class: "btn btn-primary btn-lg" %>
    </div>  
    Have an account? <%= link_to "Log in", login_path %>
    <% end %>
  </div>
  
</div>